# Generated by Django 4.0.6 on 2022-07-25 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NpcDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('age', models.PositiveIntegerField()),
                ('race', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=20)),
                ('is_alive', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('personality', models.TextField()),
                ('notes', models.TextField()),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_modified_datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
