# Generated by Django 4.0.6 on 2022-07-25 15:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NpcManager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NpcRelationshipMapper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overview', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True, null=True)),
                ('age', models.PositiveIntegerField()),
                ('ongoing', models.BooleanField(default=True)),
                ('weighting', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(-5)])),
                ('origin_npc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_npc', to='NpcManager.npcdetails')),
                ('target_npc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_npc', to='NpcManager.npcdetails')),
            ],
        ),
    ]
