# Generated by Django 4.0.6 on 2022-07-25 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NpcManager', '0002_npcrelationshipmapper'),
    ]

    operations = [
        migrations.RenameField(
            model_name='npcrelationshipmapper',
            old_name='age',
            new_name='event_age',
        ),
        migrations.AlterField(
            model_name='npcdetails',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='npcdetails',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='npcrelationshipmapper',
            name='origin_npc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_relationship', to='NpcManager.npcdetails'),
        ),
        migrations.AlterField(
            model_name='npcrelationshipmapper',
            name='target_npc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_relationship', to='NpcManager.npcdetails'),
        ),
    ]
